services:
  mongodb:
    image: mongo:7
    container_name: sumi2-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: sumi2

volumes:
  mongodb_data:
